# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Post', 'auther', 'author')
    ]
